/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * AsyncDealer - Client-side socket for request-reply pattern
 * Wraps the nng Req0Raw protocol for async operations
 */
export declare class AsyncDealer {
  /** Dial to the specified URL and establish a connection */
  static dial(url: string): Promise<AsyncDealer>
  /** Send a message and return the request ID */
  send(body: Buffer): Promise<number>
  /** Receive a message, returns DealerMessage */
  recv(): Promise<DealerMessage>
}

/**
 * AsyncRouter - Server-side socket for request-reply pattern
 * Wraps the nng Rep0Raw protocol for async operations
 */
export declare class AsyncRouter {
  /** Listen on the specified URL */
  static listen(url: string): Promise<AsyncRouter>
  /** Receive a message from a client */
  recv(): Promise<RouterMessage>
  /** Send a response message back to the client */
  send(msg: RouterMessage): Promise<void>
}

/** Message received from an AsyncDealer */
export declare class DealerMessage {
  /** Get the message body as a Buffer */
  body(): Buffer
  /** Get the message header as a Buffer */
  header(): Buffer
}

/**
 * Message received from an AsyncRouter
 * Contains identity information for routing responses back to the correct client
 */
export declare class RouterMessage {
  /** Get the client identity (first 4 bytes of header for routing) */
  identity(): Buffer | null
  /** Get the full header as a Buffer */
  header(): Buffer
  /** Get the message body as a Buffer */
  body(): Buffer
  /** Set the message body (for creating a response) */
  setBody(body: Buffer): void
  /** Create a response message with the same header (for routing) but new body */
  createResponse(body: Buffer): RouterMessage
  /** Create an empty RouterMessage (for manual construction) */
  constructor()
}

export declare function plus100(input: number): number
