/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Peer {
  static connect(url: string): Promise<Peer>
  callRaw(method: string, payload: Buffer): Promise<Buffer>
}

export declare class RawServer {
  static listen(url: string, method: string, handler: (arg: Buffer) => Buffer): RawServer
}

export declare function plus100(input: number): number
