/* auto-generated by NAPI-RS */
/* eslint-disable */
import type { Config, TypeDescription } from '@apache-fory/fory'

export interface ForySerializer<TInput = unknown, TOutput = TInput> {
  serialize(data: TInput): Uint8Array
  deserialize(bytes: Uint8Array): TOutput
}

export declare const Fory: typeof import('@apache-fory/fory').default
export declare const Type: typeof import('@apache-fory/fory').Type
export declare function createForySerializer<TInput = unknown, TOutput = TInput>(
  description: TypeDescription,
  config?: Config,
): ForySerializer<TInput, TOutput>
export declare class Peer {
  static connect(url: string): Promise<Peer>
  callRaw(method: string, payload: Buffer): Promise<Buffer>
  call<TInput = unknown, TOutput = TInput>(
    method: string,
    payload: TInput,
    serializer: ForySerializer<TInput, TOutput>,
  ): Promise<TOutput>
}

export declare class RawServer {
  static listen(url: string, method: string, handler: (arg: Buffer) => Buffer): RawServer
  static listenFory<TInput = unknown, TOutput = TInput>(
    url: string,
    method: string,
    serializer: ForySerializer<TInput, TOutput>,
    handler: (arg: TInput) => TOutput,
  ): RawServer
}

export declare function plus100(input: number): number
