// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: forpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_OK                  StatusCode = 0
	StatusCode_CANCELLED           StatusCode = 1
	StatusCode_UNKNOWN             StatusCode = 2
	StatusCode_INVALID_ARGUMENT    StatusCode = 3
	StatusCode_DEADLINE_EXCEEDED   StatusCode = 4
	StatusCode_NOT_FOUND           StatusCode = 5
	StatusCode_ALREADY_EXISTS      StatusCode = 6
	StatusCode_PERMISSION_DENIED   StatusCode = 7
	StatusCode_RESOURCE_EXHAUSTED  StatusCode = 8
	StatusCode_FAILED_PRECONDITION StatusCode = 9
	StatusCode_ABORTED             StatusCode = 10
	StatusCode_OUT_OF_RANGE        StatusCode = 11
	StatusCode_UNIMPLEMENTED       StatusCode = 12
	StatusCode_INTERNAL            StatusCode = 13
	StatusCode_UNAVAILABLE         StatusCode = 14
	StatusCode_DATA_LOSS           StatusCode = 15
	StatusCode_UNAUTHENTICATED     StatusCode = 16
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:  "OK",
		1:  "CANCELLED",
		2:  "UNKNOWN",
		3:  "INVALID_ARGUMENT",
		4:  "DEADLINE_EXCEEDED",
		5:  "NOT_FOUND",
		6:  "ALREADY_EXISTS",
		7:  "PERMISSION_DENIED",
		8:  "RESOURCE_EXHAUSTED",
		9:  "FAILED_PRECONDITION",
		10: "ABORTED",
		11: "OUT_OF_RANGE",
		12: "UNIMPLEMENTED",
		13: "INTERNAL",
		14: "UNAVAILABLE",
		15: "DATA_LOSS",
		16: "UNAUTHENTICATED",
	}
	StatusCode_value = map[string]int32{
		"OK":                  0,
		"CANCELLED":           1,
		"UNKNOWN":             2,
		"INVALID_ARGUMENT":    3,
		"DEADLINE_EXCEEDED":   4,
		"NOT_FOUND":           5,
		"ALREADY_EXISTS":      6,
		"PERMISSION_DENIED":   7,
		"RESOURCE_EXHAUSTED":  8,
		"FAILED_PRECONDITION": 9,
		"ABORTED":             10,
		"OUT_OF_RANGE":        11,
		"UNIMPLEMENTED":       12,
		"INTERNAL":            13,
		"UNAVAILABLE":         14,
		"DATA_LOSS":           15,
		"UNAUTHENTICATED":     16,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_forpc_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_forpc_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_forpc_proto_rawDescGZIP(), []int{0}
}

// FrameKind identifies the type of a Packet frame on the wire.
// Values are stable and must match across Rust/Go/Node implementations.
type FrameKind int32

const (
	FrameKind_HEADERS    FrameKind = 0
	FrameKind_DATA       FrameKind = 1
	FrameKind_TRAILERS   FrameKind = 2
	FrameKind_RST_STREAM FrameKind = 3
)

// Enum value maps for FrameKind.
var (
	FrameKind_name = map[int32]string{
		0: "HEADERS",
		1: "DATA",
		2: "TRAILERS",
		3: "RST_STREAM",
	}
	FrameKind_value = map[string]int32{
		"HEADERS":    0,
		"DATA":       1,
		"TRAILERS":   2,
		"RST_STREAM": 3,
	}
)

func (x FrameKind) Enum() *FrameKind {
	p := new(FrameKind)
	*p = x
	return p
}

func (x FrameKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameKind) Descriptor() protoreflect.EnumDescriptor {
	return file_forpc_proto_enumTypes[1].Descriptor()
}

func (FrameKind) Type() protoreflect.EnumType {
	return &file_forpc_proto_enumTypes[1]
}

func (x FrameKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameKind.Descriptor instead.
func (FrameKind) EnumDescriptor() ([]byte, []int) {
	return file_forpc_proto_rawDescGZIP(), []int{1}
}

type Call struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_forpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_forpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_forpc_proto_rawDescGZIP(), []int{0}
}

func (x *Call) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Call) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          StatusCode             `protobuf:"varint,1,opt,name=code,proto3,enum=forpc.StatusCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_forpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_forpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_forpc_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_OK
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Packet is the unit of transmission on the underlying transport.
// All fields are encoded with standard protobuf semantics; there is no
// hand-written framing on top of this message.
type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream identifier. Stream id 0 is reserved and ignored.
	StreamId uint32 `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Frame kind.
	Kind FrameKind `protobuf:"varint,2,opt,name=kind,proto3,enum=forpc.FrameKind" json:"kind,omitempty"`
	// Frame payload.
	// - HEADERS:    encoded Call message
	// - DATA:       user payload bytes
	// - TRAILERS:   encoded Status message
	// - RST_STREAM: empty (see error_code)
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Error code for RST_STREAM frames. Unused for other frame kinds.
	ErrorCode     uint32 `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_forpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_forpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_forpc_proto_rawDescGZIP(), []int{2}
}

func (x *Packet) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Packet) GetKind() FrameKind {
	if x != nil {
		return x.Kind
	}
	return FrameKind_HEADERS
}

func (x *Packet) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Packet) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

var File_forpc_proto protoreflect.FileDescriptor

const file_forpc_proto_rawDesc = "" +
	"\n" +
	"\vforpc.proto\x12\x05forpc\"\x92\x01\n" +
	"\x04Call\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x125\n" +
	"\bmetadata\x18\x02 \x03(\v2\x19.forpc.Call.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x06Status\x12%\n" +
	"\x04code\x18\x01 \x01(\x0e2\x11.forpc.StatusCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x84\x01\n" +
	"\x06Packet\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x12$\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x10.forpc.FrameKindR\x04kind\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\rR\terrorCode*\xbd\x02\n" +
	"\n" +
	"StatusCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\r\n" +
	"\tCANCELLED\x10\x01\x12\v\n" +
	"\aUNKNOWN\x10\x02\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x03\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\x04\x12\r\n" +
	"\tNOT_FOUND\x10\x05\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\x06\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\a\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\b\x12\x17\n" +
	"\x13FAILED_PRECONDITION\x10\t\x12\v\n" +
	"\aABORTED\x10\n" +
	"\x12\x10\n" +
	"\fOUT_OF_RANGE\x10\v\x12\x11\n" +
	"\rUNIMPLEMENTED\x10\f\x12\f\n" +
	"\bINTERNAL\x10\r\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x0e\x12\r\n" +
	"\tDATA_LOSS\x10\x0f\x12\x13\n" +
	"\x0fUNAUTHENTICATED\x10\x10*@\n" +
	"\tFrameKind\x12\v\n" +
	"\aHEADERS\x10\x00\x12\b\n" +
	"\x04DATA\x10\x01\x12\f\n" +
	"\bTRAILERS\x10\x02\x12\x0e\n" +
	"\n" +
	"RST_STREAM\x10\x03B'Z%github.com/bytemain/forpc/go/forpc/pbb\x06proto3"

var (
	file_forpc_proto_rawDescOnce sync.Once
	file_forpc_proto_rawDescData []byte
)

func file_forpc_proto_rawDescGZIP() []byte {
	file_forpc_proto_rawDescOnce.Do(func() {
		file_forpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forpc_proto_rawDesc), len(file_forpc_proto_rawDesc)))
	})
	return file_forpc_proto_rawDescData
}

var file_forpc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_forpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_forpc_proto_goTypes = []any{
	(StatusCode)(0), // 0: forpc.StatusCode
	(FrameKind)(0),  // 1: forpc.FrameKind
	(*Call)(nil),    // 2: forpc.Call
	(*Status)(nil),  // 3: forpc.Status
	(*Packet)(nil),  // 4: forpc.Packet
	nil,             // 5: forpc.Call.MetadataEntry
}
var file_forpc_proto_depIdxs = []int32{
	5, // 0: forpc.Call.metadata:type_name -> forpc.Call.MetadataEntry
	0, // 1: forpc.Status.code:type_name -> forpc.StatusCode
	1, // 2: forpc.Packet.kind:type_name -> forpc.FrameKind
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_forpc_proto_init() }
func file_forpc_proto_init() {
	if File_forpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forpc_proto_rawDesc), len(file_forpc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_forpc_proto_goTypes,
		DependencyIndexes: file_forpc_proto_depIdxs,
		EnumInfos:         file_forpc_proto_enumTypes,
		MessageInfos:      file_forpc_proto_msgTypes,
	}.Build()
	File_forpc_proto = out.File
	file_forpc_proto_goTypes = nil
	file_forpc_proto_depIdxs = nil
}
